# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      r: oldrel
      cran: https://mran.microsoft.com/snapshot/2018-10-14
    - os: linux
      r: release
    - os: linux
      r: devel
      warnings_are_errors: false
    - os: osx
      r: oldrel
    - os: osx
      r: release
