version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:3.5.3
    steps:
      - restore_cache:
          keys:
            - cache
      - checkout
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz
      - store_artifacts:
          path: ci4r.Rcheck/
      - save_cache:
          key: cache
          paths:
            - "/usr/local/lib/R/site-library"
