version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:3.5.3
    environment:
      R_LIBS_USER: ${HOME}/R/Library
    steps:
      - restore_cache:
          keys:
            - cache
      - checkout
      - run:
          name: Install package dependencies
          command: |
            mkdir -p ${HOME}/R/Library
            R -e 'Sys.getenv("R_LIBS_USER")'
            R -e '.libPaths()'
            R -e 'install.packages("remotes")'
            R -e 'remotes::install_deps(dependencies = TRUE)'
      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz
      - store_artifacts:
          path: ci4r.Rcheck/
      - save_cache:
          key: cache
          paths:
            - "~/R/Library"
