version: 2

steps: &steps
  steps:
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}
    - checkout
    - run:
        name: Install package dependencies
        command: R -e "devtools::install_deps(dep = TRUE)"
    - run:
        name: Build package
        command: R CMD build .
    - run:
        name: Check package
        command: R CMD check *tar.gz
    - store_artifacts:
        path: ci4r.Rcheck/
    - save_cache:
        key: cache-{{ .Environment.CIRCLE_JOB }}
        paths:
          - "/usr/local/lib/R/site-library"

jobs:
  release:
    docker:
      - image: rocker/verse:3.6.0
    <<: *steps
  oldrel:
    docker:
      - image: rocker/verse:3.5.3
    <<: *steps
  devel:
    docker:
      - image: rocker/verse:devel
    <<: *steps

workflows:
  version: 2
  all:
    jobs:
      - release
      - devel
      - oldrel
